Release 2022-08-20 10:14:22 +0900 (#174)
* 🚧  失敗するテストを追加

* 🚧  オプション消してみる

* 🐛  ファイル名を変更

以前のリネームの変更もれ

* 🔨  パイプのステータスをハンドリングする

* 🔨  pytestエラー時にもテスト結果コメントの送信は行う

* 🔨  コメントを残した後に改めてエラーハンドリングする

* Revert "🚧  失敗するテストを追加"

This reverts commit 61d3b3a51bcedd94e6725675b0e8d56a6ec050f5.

* ♻️ 不要なスペース削除

* 🚧  本番リリース時にもとりあえず コンテナで用意したDynamo DBを対象にテストする

* ✨  リリースブランチの自動生成を追加

* 🔨  Actionの実行タイミングを変更

* 🐛  masterマージ時にリリースPR作成する

* 🐛  ver修正

* 🐛  Rubyのバージョンは2.7.x

diff --git a/.github/workflows/backend-feature-fix.yaml b/.github/workflows/backend-feature-fix.yaml
--- a/.github/workflows/backend-feature-fix.yaml
+++ b/.github/workflows/backend-feature-fix.yaml
@@ -6,7 +6,12 @@ on:
       - fix/**
     paths:
       - backend/**
-      - .github/workflows/backend-feature.yaml
+      - .github/workflows/backend-feature-fix.yaml
+
+  pull_request:
+    branches:
+      - master
+    types: [closed]
 
 permissions: write-all
 
@@ -43,16 +48,20 @@ jobs:
           sh ./local-dynamo/createTable.sh
 
       - name: run pytest
+        id: pytest
+        continue-on-error: true
         working-directory: backend
         env:
-           MODE: "local"
-           AWS_DYNAMO_DB_ITEMS_TABLE_NAME : "amtest-blind-auction-items"
-           AWS_DYNAMO_DB_EVENTS_TABLE_NAME: "blind_auction_events"
-           AWS_REGION: "ap-northeast-1"
+          MODE: "local"
+          AWS_DYNAMO_DB_ITEMS_TABLE_NAME : "amtest-blind-auction-items"
+          AWS_DYNAMO_DB_EVENTS_TABLE_NAME: "blind_auction_events"
+          AWS_REGION: "ap-northeast-1"
         run: |
           pip install pytest
           pip install pytest-cov
           pytest test/ -v --cov --junitxml=pytest.xml --cov-report=term-missing:skip-covered | tee pytest-coverage.txt
+          exit ${PIPESTATUS[0]};
+
 
       - name: Create Coverage Comment
         id: coverageComment
@@ -60,3 +69,36 @@ jobs:
         with:
             pytest-coverage-path: /backend/pytest-coverage.txt
             junitxml-path: ./backend/pytest.xml
+
+      - name: Error handling
+        if: ${{steps.pytest.outcome == 'failure'}}
+        run: |
+          echo "pytest failed"
+          echo ${{steps.pytest.outcome}}
+          exit 1
+
+  CreateReleasePR:
+    name: Create relase PR
+    if: github.event.pull_request.merged == true
+    runs-on: ubuntu-latest
+    steps:
+      - name: Chechout
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0 # fetch all history to find all related pull requests.
+
+      - name: Set up Ruby 2.7
+        uses: actions/setup-ruby@v1
+        with:
+          ruby-version: 2.7.x
+
+      - name: Create a release pull request
+        env:
+          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUBACTION_TOKEN }}
+          GIT_PR_RELEASE_BRANCH_PRODUCTION: prd
+          GIT_PR_RELEASE_BRANCH_STAGING: master
+          GIT_PR_RELEASE_LABELS: release
+          TZ: Asia/Tokyo # git-pr-release write Time.now in the title.
+        run: |
+          gem install git-pr-release -v "0.6.0"
+          git-pr-release --no-fetch
